---
language: node_js
node_js:
  - "8"
  - "10"

sudo: false
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

env:
  global:
    - JOBS=1 # https://github.com/emberjs/ember.js/issues/15641
  matrix:
    - EMBER_TRY_SCENARIO=ember-lts-2.4
    - EMBER_TRY_SCENARIO=ember-lts-2.8
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - yarn global add bower # https://github.com/ember-cli/ember-try/issues/141

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
