---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

env:
  - JOBS=1 # https://github.com/emberjs/ember.js/issues/15641

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
