version: 2

jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:8-browsers
              environment:
                CHROME_BIN: "/usr/bin/google-chrome"
                JOBS: 1 # https://github.com/emberjs/ember.js/issues/15641
        steps:

            ##
            # SETUP
            ##
            - checkout

            # Bower is required because of https://github.com/ember-cli/ember-try/issues/141
            - run:
                name: Install node global dependencies
                command: |
                  sudo npm install -g yarn \
                    ember-cli \
                    bower \
                    greenkeeper-lockfile
            ##
            # NPM
            ##
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: yarn install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules

            ##
            # TESTS
            ##

            # Used for https://greenkeeper.io/ support
            - run:
                name: Greenkeeper - Update Lockfile
                command: |
                  greenkeeper-lockfile-update


            # Run Default Ember Tests
            - run:
                name: Run Ember Tests
                command: |
                  ember try:each

            # Used for https://greenkeeper.io/ support
            - run:
                name: Greenkeeper - Upload Lockfile
                command: |
                  greenkeeper-lockfile-upload
